#!/usr/bin/env bash
source .packer

# Install prerequisites:
sudo apt-get update
sudo apt-get install -y unzip

# Fetch Packer from upstream Hashicorp:
curl -o /tmp/packer_${version_packer}_linux_amd64.zip https://releases.hashicorp.com/packer/${version_packer}/packer_${version_packer}_linux_amd64.zip

# Unzip the binary:
unzip /tmp/packer_${version_packer}_linux_amd64.zip -d /tmp/

# Move binary to PATH location:
sudo mv packer /usr/local/bin/packer
sudo chown root:root /usr/local/bin/packer

# Cleanup:
rm -rf /tmp/packer_${version_packer}_linux_amd64.zip

## Summary:
packer -version