#!/bin/bash

# Install Docker CE
## Set up the repository:
sudo apt-get update && \
  sudo apt-get upgrade -y && \
  sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common

## Add Docker’s official GPG key:
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

## Add Docker apt repo:
sudo add-apt-repository \
  "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) \
  stable"

## Install Docker CE:
sudo apt-get update && \
  sudo apt-get install -y docker-ce="18.06.2~ce~3-0~ubuntu"

## Setup Docker daemon:
cat << EOF | sudo tee /etc/docker/daemon.json
{
  "exec-opts": ["native.cgroupdriver=systemd"],
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "100m"
  },
  "storage-driver": "overlay2"
}
EOF

sudo mkdir -p /etc/systemd/system/docker.service.d

# Restart docker:
sudo systemctl daemon-reload
sudo systemctl restart docker
